package org.fre18.qnt.entity;
// Generated Sep 27, 2018 10:49:54 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Customers generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "customers", catalog = "invoicespaymanents")
public class Customers implements java.io.Serializable {

	private Integer customerId;
	@JsonIgnore
	private Set orderses = new HashSet(0);
	@JsonIgnore
	private Set accountses = new HashSet(0);

	public Customers() {
	}

	public Customers(Set orderses, Set accountses) {
		this.orderses = orderses;
		this.accountses = accountses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_id", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customers", targetEntity=Orders.class)
	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customers", targetEntity=Accounts.class)
	public Set getAccountses() {
		return this.accountses;
	}

	public void setAccountses(Set accountses) {
		this.accountses = accountses;
	}

}
