package org.fre18.qnt.entity;
// Generated Sep 27, 2018 10:49:54 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * InvoiceLineItems generated by hbm2java
 */
@Entity
@Table(name = "invoice_line_items", catalog = "invoicespaymanents")
public class InvoiceLineItems implements java.io.Serializable {

	private Integer orderItemId;
	private Invoices invoices;
	private int extraTypeCode;
	private int regNumber;
	private OrderItems orderItems;

	public InvoiceLineItems() {
	}

	public InvoiceLineItems(Invoices invoices, int extraTypeCode, int regNumber) {
		this.invoices = invoices;
		this.extraTypeCode = extraTypeCode;
		this.regNumber = regNumber;
	}

	public InvoiceLineItems(Invoices invoices, int extraTypeCode, int regNumber, OrderItems orderItems) {
		this.invoices = invoices;
		this.extraTypeCode = extraTypeCode;
		this.regNumber = regNumber;
		this.orderItems = orderItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_item_id", unique = true, nullable = false)
	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invoice_number", nullable = false)
	public Invoices getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Invoices invoices) {
		this.invoices = invoices;
	}

	@Column(name = "extra_type_code", nullable = false)
	public int getExtraTypeCode() {
		return this.extraTypeCode;
	}

	public void setExtraTypeCode(int extraTypeCode) {
		this.extraTypeCode = extraTypeCode;
	}

	@Column(name = "reg_number", nullable = false)
	public int getRegNumber() {
		return this.regNumber;
	}

	public void setRegNumber(int regNumber) {
		this.regNumber = regNumber;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "invoiceLineItems")
	public OrderItems getOrderItems() {
		return this.orderItems;
	}

	public void setOrderItems(OrderItems orderItems) {
		this.orderItems = orderItems;
	}

}
