package org.fre18.qnt.entity;
// Generated Sep 27, 2018 10:49:54 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Invoices generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "invoices", catalog = "invoicespaymanents")
public class Invoices implements java.io.Serializable {

	private Integer invoiceNumber;
	private int bookingId;
	@JsonIgnore
	private Set invoiceLineItemses = new HashSet(0);
	@JsonIgnore
	private Set financialTransactionses = new HashSet(0);

	public Invoices() {
	}

	public Invoices(int bookingId) {
		this.bookingId = bookingId;
	}

	public Invoices(int bookingId, Set invoiceLineItemses, Set financialTransactionses) {
		this.bookingId = bookingId;
		this.invoiceLineItemses = invoiceLineItemses;
		this.financialTransactionses = financialTransactionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "invoice_number", unique = true, nullable = false)
	public Integer getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(Integer invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "booking_id", nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoices", targetEntity=InvoiceLineItems.class)
	public Set getInvoiceLineItemses() {
		return this.invoiceLineItemses;
	}

	public void setInvoiceLineItemses(Set invoiceLineItemses) {
		this.invoiceLineItemses = invoiceLineItemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoices",targetEntity=FinancialTransactions.class)
	public Set getFinancialTransactionses() {
		return this.financialTransactionses;
	}

	public void setFinancialTransactionses(Set financialTransactionses) {
		this.financialTransactionses = financialTransactionses;
	}

}
