package org.fre18.qnt.entity;
// Generated Sep 27, 2018 10:49:54 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Products generated by hbm2java
 */
@Entity
@Proxy(lazy = false)
@Table(name = "products", catalog = "invoicespaymanents")
public class Products implements java.io.Serializable {

	private Integer productId;
	private Products products;
	@JsonIgnore
	private Set orderItemses = new HashSet(0);
	@JsonIgnore
	private Set productses = new HashSet(0);

	public Products() {
	}

	public Products(Products products) {
		this.products = products;
	}

	public Products(Products products, Set orderItemses, Set productses) {
		this.products = products;
		this.orderItemses = orderItemses;
		this.productses = productses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_id", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "products_product_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products", targetEntity=OrderItems.class)
	public Set getOrderItemses() {
		return this.orderItemses;
	}

	public void setOrderItemses(Set orderItemses) {
		this.orderItemses = orderItemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products", targetEntity=Products.class)
	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
