package org.fre18.qnt.entity;
// Generated Sep 27, 2018 10:49:54 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionTypes generated by hbm2java
 */
@Entity
@Table(name = "transaction_types", catalog = "invoicespaymanents")
public class TransactionTypes implements java.io.Serializable {

	private Integer transactionTypeCode;
	private Set financialTransactionses = new HashSet(0);

	public TransactionTypes() {
	}

	public TransactionTypes(Set financialTransactionses) {
		this.financialTransactionses = financialTransactionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "transaction_type_code", unique = true, nullable = false)
	public Integer getTransactionTypeCode() {
		return this.transactionTypeCode;
	}

	public void setTransactionTypeCode(Integer transactionTypeCode) {
		this.transactionTypeCode = transactionTypeCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactionTypes")
	public Set getFinancialTransactionses() {
		return this.financialTransactionses;
	}

	public void setFinancialTransactionses(Set financialTransactionses) {
		this.financialTransactionses = financialTransactionses;
	}

}
