package com.fre18.qnt.model;
// Generated Sep 27, 2018 12:07:48 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Invoices generated by hbm2java
 */
@Entity
@Table(name = "invoices", catalog = "invoicespaymanents")
public class Invoices implements java.io.Serializable {

	private Integer invoiceNumber;
	private int bookingId;
	private Set<InvoiceLineItems> invoiceLineItemses = new HashSet<InvoiceLineItems>(0);
	private Set<FinancialTransactions> financialTransactionses = new HashSet<FinancialTransactions>(0);

	public Invoices() {
	}

	public Invoices(int bookingId) {
		this.bookingId = bookingId;
	}

	public Invoices(int bookingId, Set<InvoiceLineItems> invoiceLineItemses,
			Set<FinancialTransactions> financialTransactionses) {
		this.bookingId = bookingId;
		this.invoiceLineItemses = invoiceLineItemses;
		this.financialTransactionses = financialTransactionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "invoice_number", unique = true, nullable = false)
	public Integer getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(Integer invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Column(name = "booking_id", nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoices")
	public Set<InvoiceLineItems> getInvoiceLineItemses() {
		return this.invoiceLineItemses;
	}

	public void setInvoiceLineItemses(Set<InvoiceLineItems> invoiceLineItemses) {
		this.invoiceLineItemses = invoiceLineItemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoices")
	public Set<FinancialTransactions> getFinancialTransactionses() {
		return this.financialTransactionses;
	}

	public void setFinancialTransactionses(Set<FinancialTransactions> financialTransactionses) {
		this.financialTransactionses = financialTransactionses;
	}

}
