/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;

import java.util.List;

import org.fre18.qnt.entity.Accounts;

public interface AccountsService {

	public Accounts getOne(Integer accountId);

	public List<Accounts> findAll();

	public Boolean delete(Integer accountId);

	public Accounts create(Accounts accounts);

	//public Accounts update(Accounts accounts);

	public Boolean exist(Accounts accounts);
}
