/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;


import java.util.List;

import javax.transaction.Transactional;

import org.fre18.qnt.entity.Accounts;
import org.fre18.qnt.repository.AccountsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class AccountsServiceImpl implements AccountsService {

	@Autowired
	private AccountsRepository accountsRepository;

	@Override
	public Accounts getOne(Integer accountId) {
		return accountsRepository.getOne(accountId);
	}

	@Override
	public Boolean delete(Integer accountId) {
		if (accountsRepository.getOne(accountId) != null) {
			accountsRepository.deleteById(accountId);
			return true;
		}
		return false;
	}

	@Override
	public Accounts create(Accounts accounts) {
		return accountsRepository.save(accounts);
	}

	@Override
	public Accounts update(Accounts accountsToUpdate) {
						Accounts accounts = accountsRepository.getOne(accountsToUpdate.getAccountId());
										
				if(accountsToUpdate.getCustomers() !=null) {
			
		}
				return accountsRepository.save(accounts);
	}

	@Override
	public Boolean exist(Accounts accounts) {
						return accountsRepository.existsById(accounts.getAccountId());
									}

	@Override
	public List<Accounts> findAll() {
		return accountsRepository.findAll();
	}

}

