/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;


import java.util.List;

import javax.transaction.Transactional;

import org.fre18.qnt.entity.Customers;
import org.fre18.qnt.repository.CustomersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class CustomersServiceImpl implements CustomersService {

	@Autowired
	private CustomersRepository customersRepository;

	@Override
	public Customers getOne(Integer customerId) {
		return customersRepository.getOne(customerId);
	}

	@Override
	public Boolean delete(Integer customerId) {
		if (customersRepository.getOne(customerId) != null) {
			customersRepository.deleteById(customerId);
			return true;
		}
		return false;
	}

	@Override
	public Customers create(Customers customers) {
		return customersRepository.save(customers);
	}

	@Override
	public Customers update(Customers customersToUpdate) {
						Customers customers = customersRepository.getOne(customersToUpdate.getCustomerId());
						
				return customersRepository.save(customers);
	}

	@Override
	public Boolean exist(Customers customers) {
						return customersRepository.existsById(customers.getCustomerId());
					}

	@Override
	public List<Customers> findAll() {
		return customersRepository.findAll();
	}

}

