/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;

import java.util.List;

import org.fre18.qnt.entity.FinancialTransactions;

public interface FinancialTransactionsService {

	public FinancialTransactions getOne(Integer transactionId);

	public List<FinancialTransactions> findAll();

	public Boolean delete(Integer transactionId);

	public FinancialTransactions create(FinancialTransactions financialTransactions);

	public FinancialTransactions update(FinancialTransactions financialTransactions);

	public Boolean exist(FinancialTransactions financialTransactions);
}
