/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;


import java.util.List;

import javax.transaction.Transactional;

import org.fre18.qnt.entity.FinancialTransactions;
import org.fre18.qnt.repository.FinancialTransactionsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class FinancialTransactionsServiceImpl implements FinancialTransactionsService {

	@Autowired
	private FinancialTransactionsRepository financialTransactionsRepository;

	@Override
	public FinancialTransactions getOne(Integer transactionId) {
		return financialTransactionsRepository.getOne(transactionId);
	}

	@Override
	public Boolean delete(Integer transactionId) {
		if (financialTransactionsRepository.getOne(transactionId) != null) {
			financialTransactionsRepository.deleteById(transactionId);
			return true;
		}
		return false;
	}

	@Override
	public FinancialTransactions create(FinancialTransactions financialTransactions) {
		return financialTransactionsRepository.save(financialTransactions);
	}

	@Override
	public FinancialTransactions update(FinancialTransactions financialTransactionsToUpdate) {
						FinancialTransactions financialTransactions = financialTransactionsRepository.getOne(financialTransactionsToUpdate.getTransactionId());
																		
				if(financialTransactionsToUpdate.getAccounts() !=null) {
			
		}
				if(financialTransactionsToUpdate.getInvoices() !=null) {
			
		}
				if(financialTransactionsToUpdate.getTransactionId() !=null) {
			
		}
				return financialTransactionsRepository.save(financialTransactions);
	}

	@Override
	public Boolean exist(FinancialTransactions financialTransactions) {
						return financialTransactionsRepository.existsById(financialTransactions.getTransactionId());
																	}

	@Override
	public List<FinancialTransactions> findAll() {
		return financialTransactionsRepository.findAll();
	}

}

