/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;


import java.util.List;

import javax.transaction.Transactional;

import org.fre18.qnt.entity.InvoiceLineItems;
import org.fre18.qnt.repository.InvoiceLineItemsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class InvoiceLineItemsServiceImpl implements InvoiceLineItemsService {

	@Autowired
	private InvoiceLineItemsRepository invoiceLineItemsRepository;

	@Override
	public InvoiceLineItems getOne(Integer orderItemId) {
		return invoiceLineItemsRepository.getOne(orderItemId);
	}

	@Override
	public Boolean delete(Integer orderItemId) {
		if (invoiceLineItemsRepository.getOne(orderItemId) != null) {
			invoiceLineItemsRepository.deleteById(orderItemId);
			return true;
		}
		return false;
	}

	@Override
	public InvoiceLineItems create(InvoiceLineItems invoiceLineItems) {
		return invoiceLineItemsRepository.save(invoiceLineItems);
	}

	@Override
	public InvoiceLineItems update(InvoiceLineItems invoiceLineItemsToUpdate) {
						InvoiceLineItems invoiceLineItems = invoiceLineItemsRepository.getOne(invoiceLineItemsToUpdate.getOrderItemId());
																		
				/*if(invoiceLineItemsToUpdate.getExtraTypeCode() ==0) {
			
		}
				if(invoiceLineItemsToUpdate.getInvoiceNumber() !=null) {
			
		}
				if(invoiceLineItemsToUpdate.getRegNumber() !=null) {
			
		}*/
				return invoiceLineItemsRepository.save(invoiceLineItems);
	}

	@Override
	public Boolean exist(InvoiceLineItems invoiceLineItems) {
						return invoiceLineItemsRepository.existsById(invoiceLineItems.getOrderItemId());
																	}

	@Override
	public List<InvoiceLineItems> findAll() {
		return invoiceLineItemsRepository.findAll();
	}

}

