/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;

import java.util.List;

import org.fre18.qnt.entity.InvoiceLineItems;

public interface InvoiceLineItemsService {

	public InvoiceLineItems getOne(Integer orderItemId);

	public List<InvoiceLineItems> findAll();

	public Boolean delete(Integer orderItemId);

	public InvoiceLineItems create(InvoiceLineItems invoiceLineItems);

	public InvoiceLineItems update(InvoiceLineItems invoiceLineItems);

	public Boolean exist(InvoiceLineItems invoiceLineItems);
}
