/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;

import org.fre18.qnt.entity.Invoices;
import java.util.List;

public interface InvoicesService {

	public Invoices getOne(Integer invoiceNumber);

	public List<Invoices> findAll();

	public Boolean delete(Integer invoiceNumber);

	public Invoices create(Invoices invoices);

	public Invoices update(Invoices invoices);

	public Boolean exist(Invoices invoices);
}
