/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;


import java.util.List;

import javax.transaction.Transactional;

import org.fre18.qnt.entity.OrderItems;
import org.fre18.qnt.repository.OrderItemsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class OrderItemsServiceImpl implements OrderItemsService {

	@Autowired
	private OrderItemsRepository orderItemsRepository;

	@Override
	public OrderItems getOne(Integer orderItemId) {
		return orderItemsRepository.getOne(orderItemId);
	}

	@Override
	public Boolean delete(Integer orderItemId) {
		if (orderItemsRepository.getOne(orderItemId) != null) {
			orderItemsRepository.deleteById(orderItemId);
			return true;
		}
		return false;
	}

	@Override
	public OrderItems create(OrderItems orderItems) {
		return orderItemsRepository.save(orderItems);
	}

	@Override
	public OrderItems update(OrderItems orderItemsToUpdate) {
						OrderItems orderItems = orderItemsRepository.getOne(orderItemsToUpdate.getOrderItemId());
														
				/*if(orderItemsToUpdate.getOrderId() !=null) {
			
		}
				if(orderItemsToUpdate.getProductId() !=null) {
			
		}*/
				return orderItemsRepository.save(orderItems);
	}

	@Override
	public Boolean exist(OrderItems orderItems) {
						return orderItemsRepository.existsById(orderItems.getOrderItemId());
													}

	@Override
	public List<OrderItems> findAll() {
		return orderItemsRepository.findAll();
	}

}

