/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;

import org.fre18.qnt.entity.OrderItems;
import java.util.List;

public interface OrderItemsService {

	public OrderItems getOne(Integer orderItemId);

	public List<OrderItems> findAll();

	public Boolean delete(Integer orderItemId);

	public OrderItems create(OrderItems orderItems);

	public OrderItems update(OrderItems orderItems);

	public Boolean exist(OrderItems orderItems);
}
