/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;


import java.util.List;

import javax.transaction.Transactional;

import org.fre18.qnt.entity.Orders;
import org.fre18.qnt.repository.OrdersRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class OrdersServiceImpl implements OrdersService {

	@Autowired
	private OrdersRepository ordersRepository;

	@Override
	public Orders getOne(Integer orderId) {
		return ordersRepository.getOne(orderId);
	}

	@Override
	public Boolean delete(Integer orderId) {
		if (ordersRepository.getOne(orderId) != null) {
			ordersRepository.deleteById(orderId);
			return true;
		}
		return false;
	}

	@Override
	public Orders create(Orders orders) {
		return ordersRepository.save(orders);
	}

	@Override
	public Orders update(Orders ordersToUpdate) {
						Orders orders = ordersRepository.getOne(ordersToUpdate.getOrderId());
										
				/*if(ordersToUpdate.getCustomerId() !=null) {
			
		}*/
				return ordersRepository.save(orders);
	}

	@Override
	public Boolean exist(Orders orders) {
						return ordersRepository.existsById(orders.getOrderId());
									}

	@Override
	public List<Orders> findAll() {
		return ordersRepository.findAll();
	}

}

