/*
 * Created on 2018-09-27 ( Date ISO 2018-09-27 - Time 11:32:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.fre18.qnt.service;

import java.util.List;

import org.fre18.qnt.entity.Orders;

public interface OrdersService {

	public Orders getOne(Integer orderId);

	public List<Orders> findAll();

	public Boolean delete(Integer orderId);

	public Orders create(Orders orders);

	public Orders update(Orders orders);

	public Boolean exist(Orders orders);
}
